<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findAllByCriteria($isbn = '', $author = '')
    {
        $query = $this->createQueryBuilder('book')
            ->leftJoin('book.author', 'author');

        if($isbn) {
            $query->andWhere('book.isbn LIKE :isbn')
                ->setParameter('isbn', '%' . $isbn . '%');
        }

        if ($author) {
            $query->andWhere('author.name = :author')
                ->setParameter('author', $author);
        }

        return $query->orderBy('book.price', 'ASC')
            ->getQuery()
            ->execute();
    }
}
